kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
  namespace: nginx
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 0.5Gi
